/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardGroup: typeof import('bootstrap-vue-next/components/BCard')['BCardGroup']
    BCardImg: typeof import('bootstrap-vue-next/components/BCard')['BCardImg']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormFile: typeof import('bootstrap-vue-next/components/BFormFile')['BFormFile']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormRadio: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadio']
    BFormRadioGroup: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadioGroup']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BFormSelectOption: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelectOption']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BImg: typeof import('bootstrap-vue-next/components/BImg')['BImg']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BListGroup: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BModalOrchestrator: typeof import('bootstrap-vue-next/components/BModal')['BModalOrchestrator']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    BPopover: typeof import('bootstrap-vue-next/components/BPopover')['BPopover']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    BToastOrchestrator: typeof import('bootstrap-vue-next/components/BToast')['BToastOrchestrator']
    BTooltip: typeof import('bootstrap-vue-next/components/BTooltip')['BTooltip']
  }
  export interface ComponentCustomProperties {
    vBModal: typeof import('bootstrap-vue-next/directives/BModal')['vBModal']
    vBToggle: typeof import('bootstrap-vue-next/directives/BToggle')['vBToggle']
  }
}
